version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeperStudy
    ports:
      - "2181:2181"
    networks:
      - talk-platform-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafkaStudy
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    networks:
      - talk-platform-net

networks:
  talk-platform-net:
    driver: bridge
